//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltHealthDBLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientData()
        {
            this.InvoiceInfo = new HashSet<InvoiceInfo>();
        }
    
        public double Client_id { get; set; }
        public string C_name { get; set; }
        public string C_surname { get; set; }
        public string Address { get; set; }
        public Nullable<int> Code { get; set; }
        public string C_Tel_H { get; set; }
        public string C_Tel_W { get; set; }
        public string C_Tel_Cell { get; set; }
        public string C_Email { get; set; }
        public string C_Reference { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceInfo> InvoiceInfo { get; set; }
    }
}
