//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltHealthDBLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceItem
    {
        public int InvItemID { get; set; }
        public Nullable<int> InvID { get; set; }
        public string Suppl_id { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual InvoiceInfo InvoiceInfo { get; set; }
        public virtual Supplement Supplement { get; set; }
    }
}
