//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltHealthDBLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvoiceInfo()
        {
            this.InvoiceItems = new HashSet<InvoiceItem>();
        }
    
        public int InvID { get; set; }
        public string INVNum { get; set; }
        public Nullable<System.DateTime> INVDate { get; set; }
        public Nullable<double> Client_id { get; set; }
        public Nullable<decimal> Consultation { get; set; }
        public Nullable<decimal> TotalSupplements { get; set; }
        public Nullable<decimal> TotalSupplConsultation { get; set; }
    
        public virtual ClientData ClientData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceItem> InvoiceItems { get; set; }
    }
}
