//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltHealthDBLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppl_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Suppl_Info()
        {
            this.Supplements = new HashSet<Supplement>();
        }
    
        public string Supplier_id { get; set; }
        public string Contact_Person { get; set; }
        public string Tel { get; set; }
        public string Cell { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Bank { get; set; }
        public Nullable<int> Branch_Code { get; set; }
        public Nullable<double> Account_Number { get; set; }
        public string Type_of_Account { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplement> Supplements { get; set; }
    }
}
