//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltHealthDBLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplement()
        {
            this.InvoiceItems = new HashSet<InvoiceItem>();
        }
    
        public string Suppl_id { get; set; }
        public string Description { get; set; }
        public decimal Cost_excl { get; set; }
        public decimal Cost_incl { get; set; }
        public Nullable<decimal> Perc_inc { get; set; }
        public decimal Cost_client { get; set; }
        public string Supplier_id { get; set; }
        public int Min_levels { get; set; }
        public int Stock_levels { get; set; }
        public string Nappi_code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceItem> InvoiceItems { get; set; }
        public virtual Suppl_Info Suppl_Info { get; set; }
    }
}
